(()=>{
'use strict';
const API=(window.POS_CONFIG?.API_BASE||'').replace(/\/$/,'');
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const peso=n=>Number(n)>0?new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP',maximumFractionDigits:0}).format(Number(n)):'Ask for Quote';
const slug=v=>String(v||'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const fmt=v=>v?new Date(v).toLocaleString('en-PH',{year:'numeric',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'—';
const PUBLIC_REFRESH_MS=60000;
const TRACK_REFRESH_MS=15000;
let publicRefreshTimer=null;
let trackingRefreshTimer=null;
let publicRefreshBusy=false;
let trackingRefreshBusy=false;
let trackedPayload=null;
let data={settings:{},categories:[],brands:[],products:[],packages:[],reviews:[]}, activeCategory='', activeBrand='all';
function notify(msg,type=''){const t=$('#toast');t.textContent=msg;t.className='toast show '+type;clearTimeout(notify.timer);notify.timer=setTimeout(()=>t.className='toast',3000)}
async function api(path,options={}){if(!API||API.includes('REPLACE-WITH'))throw new Error('API is not configured yet. Open config.js and add the Cloudflare Worker URL.');const res=await fetch(API+path,{...options,headers:{...(options.body instanceof FormData?{}:{'Content-Type':'application/json'}),...(options.headers||{})}});let body={};try{body=await res.json()}catch{}if(!res.ok)throw new Error(body.error||`Request failed (${res.status})`);return body}
function fallbackLogo(name='POS Philippines'){return `<div class="brand-fallback">${esc(name).split(/\s+/).map(x=>x[0]).join('').slice(0,3).toUpperCase()}</div>`}
function imgOrPlaceholder(url,name,cls=''){return url?`<img class="${cls}" src="${esc(url)}" alt="${esc(name)}" loading="lazy">`:`<div class="image-placeholder">${esc(name)}</div>`}
function category(id){return data.categories.find(x=>x.id===id)}function brand(id){return data.brands.find(x=>x.id===id)}function product(id){return data.products.find(x=>x.id===id)}
function openDialog(id){const d=$('#'+id);if(d&&!d.open)d.showModal()}
async function load(showError=true){if(publicRefreshBusy)return;publicRefreshBusy=true;const previous={category:$('#inqCategory')?.value||'',brand:$('#inqBrand')?.value||'',product:$('#inqProduct')?.value||''};try{data=await api('/api/public/bootstrap');renderAll(previous)}catch(err){if(showError){notify(err.message,'error');$('#heroSubtitle').textContent=err.message;$('#categoryGrid').innerHTML=`<div class="empty" style="grid-column:1/-1">${esc(err.message)}</div>`;$('#productGrid').innerHTML='';$('#packageGrid').innerHTML=''}else console.warn('Customer auto-refresh failed:',err.message)}finally{publicRefreshBusy=false}}
function renderAll(previous={}){renderSettings();const cats=data.categories.filter(x=>x.is_active).sort((a,b)=>a.display_order-b.display_order);if(!cats.some(x=>x.id===activeCategory))activeCategory=cats[0]?.id||'';renderCatalog();renderPackages();renderReviews();fillInquiryCategories(previous.category,previous.brand,previous.product)}
function renderSettings(){const s=data.settings||{}, name=s.business_name||'POS Philippines';document.title=name;$('#brandName').innerHTML=esc(name).replace(/^POS/i,'<span>POS</span>');$('#brandLogo').innerHTML=s.logo_url?`<img class="brand-logo" src="${esc(s.logo_url)}" alt="${esc(name)}">`:fallbackLogo(name);$('#footerLogo').innerHTML=s.logo_url?`<img src="${esc(s.logo_url)}" alt="${esc(name)}" style="width:120px;height:80px;object-fit:contain;background:#fff;border-radius:13px;padding:5px;margin-bottom:12px">`:fallbackLogo(name);$('#footerBusinessName').textContent=name;$('#footerTagline').textContent=s.tagline||'Your Business. Our Solutions.';$('#copyrightName').textContent=name;$('#year').textContent=new Date().getFullYear();$('#heroSubtitle').textContent=s.hero_subtitle||'POS Systems, CCTV, Biometrics, Solar and more. Quality products, affordable prices, and reliable after-sales support.';if(s.hero_title)$('#heroTitle').textContent=s.hero_title;if(s.hero_image_url)$('#heroArt').innerHTML=`<img src="${esc(s.hero_image_url)}" alt="${esc(name)}">`;$('#phoneButton').textContent=s.phone?`☎ ${s.phone}`:'Contact';$('#phoneButton').href=s.phone?`tel:${s.phone}`:'#inquiry';$('#facebookLink').textContent=`FB Page: ${s.facebook_name||name}`;$('#facebookLink').href=s.facebook_url||'#';$('#emailLink').textContent=`Email: ${s.email||''}`;$('#emailLink').href=s.email?`mailto:${s.email}`:'#';$('#contactLink').textContent=`Contact #: ${s.phone||''}`;$('#contactLink').href=s.phone?`tel:${s.phone}`:'#';$('#addressText').textContent=s.address||''}
function renderCatalog(){const cats=data.categories.filter(x=>x.is_active).sort((a,b)=>a.display_order-b.display_order);if(!cats.some(x=>x.id===activeCategory))activeCategory=cats[0]?.id||'';$('#categoryGrid').innerHTML=cats.map(c=>`<button class="category-card ${c.id===activeCategory?'active':''}" data-cat="${c.id}">${c.image_url?`<img src="${esc(c.image_url)}" alt="${esc(c.name)}" loading="lazy">`:`<div class="category-placeholder">${esc(c.name).slice(0,4).toUpperCase()}</div>`}<strong>${esc(c.name)}</strong></button>`).join('')||'<div class="empty" style="grid-column:1/-1">No categories available.</div>';$$('#categoryGrid [data-cat]').forEach(b=>b.onclick=()=>{activeCategory=b.dataset.cat;activeBrand='all';renderCatalog()});const brands=data.brands.filter(x=>x.is_active&&x.category_id===activeCategory).sort((a,b)=>a.display_order-b.display_order);$('#brandBar').innerHTML=`<button class="brand-filter ${activeBrand==='all'?'active':''}" data-brand="all">All Brands</button>`+brands.map(b=>`<button class="brand-filter ${activeBrand===b.id?'active':''}" data-brand="${b.id}">${esc(b.name)}</button>`).join('');$$('#brandBar [data-brand]').forEach(b=>b.onclick=()=>{activeBrand=b.dataset.brand;renderCatalog()});const c=category(activeCategory), products=data.products.filter(x=>x.is_available&&x.category_id===activeCategory&&(activeBrand==='all'||x.brand_id===activeBrand));$('#productContext').textContent=(c?.name||'Products')+(activeBrand!=='all'?' • '+(brand(activeBrand)?.name||''):'');$('#productTitle').innerHTML=esc(c?.name||'Available')+' <span>Products</span>';$('#productGrid').innerHTML=products.map(p=>`<article class="product-card"><div class="product-image">${imgOrPlaceholder(p.image_url,p.name)}</div><div class="product-body"><div class="product-meta">${esc(brand(p.brand_id)?.name||'POS Philippines')}</div><h3>${esc(p.name)}</h3><p>${esc(p.short_description||p.description||'')}</p><div class="product-bottom"><span class="price">${peso(p.price)}</span><button class="btn btn-blue btn-sm" data-product="${p.id}">View Details</button></div></div></article>`).join('')||'<div class="empty" style="grid-column:1/-1">No products available in this category yet.</div>';$$('#productGrid [data-product]').forEach(b=>b.onclick=()=>showProduct(b.dataset.product))}
function showProduct(id){const p=product(id);if(!p)return;$('#productDialogTitle').textContent=p.name;$('#productDialogBody').innerHTML=`<div style="display:grid;grid-template-columns:minmax(180px,.7fr) 1.3fr;gap:18px;align-items:start"><div style="height:220px">${imgOrPlaceholder(p.image_url,p.name)}</div><div><span class="eyebrow">${esc(category(p.category_id)?.name||'')} • ${esc(brand(p.brand_id)?.name||'')}</span><h2>${esc(p.name)}</h2><div class="price">${peso(p.price)}</div><p class="muted" style="line-height:1.7">${esc(p.description||p.short_description||'')}</p><a href="#inquiry" class="btn btn-primary" id="inquireProduct">Inquire About This Product</a></div></div>`;openDialog('productDialog');$('#inquireProduct').onclick=()=>{$('#productDialog').close();setTimeout(()=>{$('#inquiry').scrollIntoView();$('#inqCategory').value=p.category_id;fillInquiryBrands(p.brand_id,p.id)},100)}}
function renderPackages(){const list=data.packages.filter(x=>x.is_active).sort((a,b)=>a.display_order-b.display_order);$('#packageGrid').innerHTML=list.map(p=>`<article class="package-card panel ${p.is_featured?'popular':''}">${p.is_featured?'<span class="popular-tag">MOST POPULAR</span>':''}<div class="package-image">${imgOrPlaceholder(p.image_url,p.name)}</div><span class="eyebrow">${esc(p.subtitle||'POS Package')}</span><h3>${esc(p.name)}</h3><div class="package-price">${peso(p.price)}</div><ul class="package-list">${(p.inclusions||[]).map(i=>`<li>${esc(i)}</li>`).join('')}</ul><a href="#inquiry" class="btn ${p.is_featured?'btn-blue':'btn-outline'} btn-block">Request This Package</a></article>`).join('')||'<div class="empty" style="grid-column:1/-1">No packages available.</div>'}
function renderReviews(){const list=data.reviews||[];$('#reviewList').innerHTML=list.map(r=>`<article class="review-card">${r.image_url?`<img src="${esc(r.image_url)}" alt="Review image" loading="lazy">`:''}<div class="stars">${'★'.repeat(Number(r.rating))}${'☆'.repeat(5-Number(r.rating))}</div><h4>${esc(r.name)} ${r.business?`<span class="small muted">• ${esc(r.business)}</span>`:''}</h4><p>${esc(r.message)}</p></article>`).join('')||'<div class="empty">No approved customer reviews yet.</div>'}
function fillInquiryCategories(selectedCategory='',selectedBrand='',selectedProduct=''){const f=$('#inqCategory');f.innerHTML='<option value="">Select category</option>'+data.categories.filter(x=>x.is_active).sort((a,b)=>a.display_order-b.display_order).map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');if(selectedCategory&&data.categories.some(c=>c.id===selectedCategory&&c.is_active))f.value=selectedCategory;fillInquiryBrands(selectedBrand,selectedProduct)}
function fillInquiryBrands(selectedBrand='',selectedProduct=''){const cid=$('#inqCategory').value, f=$('#inqBrand'), list=data.brands.filter(x=>x.is_active&&x.category_id===cid);f.innerHTML='<option value="">Any brand</option>'+list.map(b=>`<option value="${b.id}">${esc(b.name)}</option>`).join('');if(selectedBrand)f.value=selectedBrand;fillInquiryProducts(selectedProduct)}
function fillInquiryProducts(selected=''){const cid=$('#inqCategory').value,bid=$('#inqBrand').value,list=data.products.filter(x=>x.is_available&&x.category_id===cid&&(!bid||x.brand_id===bid));$('#inqProduct').innerHTML='<option value="">Select product/service</option>'+list.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');if(selected)$('#inqProduct').value=selected}
async function submitInquiry(e){e.preventDefault();const f=e.currentTarget, payload=Object.fromEntries(new FormData(f));try{const r=await api('/api/inquiries',{method:'POST',body:JSON.stringify(payload)});$('#inquiryResult').innerHTML=`<div class="result-box"><b>Inquiry submitted successfully!</b><p style="margin:7px 0">Your tracking number is:</p><div style="font-size:22px;font-weight:1000;color:var(--blue)">${esc(r.tracking)}</div><p class="small muted">Save this together with your email or mobile number.</p></div>`;$('#trackingForm [name=tracking]').value=r.tracking;$('#trackingForm [name=contact]').value=payload.email;f.reset();fillInquiryCategories();notify('Inquiry submitted.','success')}catch(err){notify(err.message,'error')}}
function renderTrackingResult(q){$('#trackingResult').innerHTML=`<div class="result-box"><div style="display:flex;justify-content:space-between;gap:10px;align-items:center"><b>${esc(q.tracking)}</b><span class="status ${slug(q.status)}">${esc(q.status)}</span></div><p class="small">${esc(q.public_note||'No public update yet.')}</p><p class="small muted">Last updated: ${fmt(q.updated_at)} • Auto-refresh every 15 seconds</p><div class="timeline">${(q.history||[]).map(h=>`<div class="timeline-item"><span class="timeline-dot"></span><div><b>${esc(h.status)}</b><small>${esc(h.note||'')} • ${fmt(h.created_at)}</small></div></div>`).join('')}</div></div>`}
async function refreshTrackedInquiry(showError=false){if(!trackedPayload||trackingRefreshBusy||document.visibilityState!=='visible')return;trackingRefreshBusy=true;try{const q=await api('/api/inquiries/track',{method:'POST',body:JSON.stringify(trackedPayload)});renderTrackingResult(q)}catch(err){if(showError)$('#trackingResult').innerHTML=`<div class="result-box" style="background:#fff0f0;border-color:#efc2c2"><b>${esc(err.message)}</b></div>`;else console.warn('Tracking auto-refresh failed:',err.message)}finally{trackingRefreshBusy=false}}
async function trackInquiry(e){e.preventDefault();trackedPayload=Object.fromEntries(new FormData(e.currentTarget));await refreshTrackedInquiry(true)}
async function submitReview(e){e.preventDefault();const f=e.currentTarget, fd=new FormData(f);try{let image_url='';const file=fd.get('image');if(file&&file.size){const up=new FormData();up.append('file',file);up.append('tracking',fd.get('tracking'));up.append('contact',fd.get('contact'));const result=await api('/api/public/review-upload',{method:'POST',body:up});image_url=result.url}const payload={tracking:fd.get('tracking'),contact:fd.get('contact'),name:fd.get('name'),business:fd.get('business'),rating:Number(fd.get('rating')),message:fd.get('message'),image_url};await api('/api/reviews',{method:'POST',body:JSON.stringify(payload)});$('#reviewResult').innerHTML='<div class="result-box"><b>Review submitted.</b><p class="small">It will appear after admin approval.</p></div>';f.reset();notify('Review sent for approval.','success')}catch(err){$('#reviewResult').innerHTML=`<div class="result-box" style="background:#fff0f0;border-color:#efc2c2">${esc(err.message)}</div>`}}
$('#menuToggle').onclick=()=>$('#navLinks').classList.toggle('open');$$('#navLinks a').forEach(a=>a.onclick=()=>$('#navLinks').classList.remove('open'));$('#inqCategory').onchange=()=>fillInquiryBrands();$('#inqBrand').onchange=()=>fillInquiryProducts();$('#inquiryForm').onsubmit=submitInquiry;$('#trackingForm').onsubmit=trackInquiry;$('#openReview').onclick=()=>{const f=$('#reviewForm');f.reset();$('#reviewResult').innerHTML='';openDialog('reviewDialog')};$('#reviewForm').onsubmit=submitReview;$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close)?.close());document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d)d.close()}));
function startCustomerAutoRefresh(){clearInterval(publicRefreshTimer);clearInterval(trackingRefreshTimer);publicRefreshTimer=setInterval(()=>{if(document.visibilityState==='visible'&&!document.querySelector('dialog[open]'))load(false)},PUBLIC_REFRESH_MS);trackingRefreshTimer=setInterval(()=>refreshTrackedInquiry(false),TRACK_REFRESH_MS)}
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'){load(false);refreshTrackedInquiry(false)}});
load().then(startCustomerAutoRefresh);
})();
